// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/asset-statuses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-statuses"
                ],
                "summary": "List asset statuses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetStatusPage"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-statuses"
                ],
                "summary": "Create an asset status",
                "parameters": [
                    {
                        "description": "Asset status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAssetStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/asset-statuses/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-statuses"
                ],
                "summary": "Get an asset status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Asset status id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetStatusResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-statuses"
                ],
                "summary": "Update an asset status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Asset status id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Asset status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAssetStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetStatusResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "asset-statuses"
                ],
                "summary": "Delete an asset status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Asset status id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/asset-types": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-types"
                ],
                "summary": "List asset types",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetTypePage"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-types"
                ],
                "summary": "Create an asset type",
                "parameters": [
                    {
                        "description": "Asset type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAssetTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetTypeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/asset-types/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-types"
                ],
                "summary": "Get an asset type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Asset type id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetTypeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-types"
                ],
                "summary": "Update an asset type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Asset type id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Asset type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAssetTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetTypeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "asset-types"
                ],
                "summary": "Delete an asset type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Asset type id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/assets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "List assets",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetPage"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Create assets",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/assets/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Get assets",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Update assets",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Delete assets",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/catalog-options": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog-options"
                ],
                "summary": "List catalog options",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CatalogOptionPage"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog-options"
                ],
                "summary": "Create a catalog option",
                "parameters": [
                    {
                        "description": "Catalog option",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCatalogOptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CatalogOptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/catalog-options/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog-options"
                ],
                "summary": "Get a catalog option",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Catalog option id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CatalogOptionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog-options"
                ],
                "summary": "Update a catalog option",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Catalog option id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Catalog option",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCatalogOptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CatalogOptionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "catalog-options"
                ],
                "summary": "Delete a catalog option",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Catalog option id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/companies": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "companies"
                ],
                "summary": "List companies (paginated)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CompanyPage"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "companies"
                ],
                "summary": "Create a company",
                "parameters": [
                    {
                        "description": "Company",
                        "name": "company",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CompanyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/companies/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "companies"
                ],
                "summary": "Get a company by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Company id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CompanyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "companies"
                ],
                "summary": "Update a company",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Company id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Company",
                        "name": "company",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CompanyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "companies"
                ],
                "summary": "Delete a company",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Company id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/uploads": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Upload a file (image) to object storage",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/storage.Object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vehicle-makes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-makes"
                ],
                "summary": "List vehicle makes",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleMakePage"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-makes"
                ],
                "summary": "Create a vehicle make",
                "parameters": [
                    {
                        "description": "Vehicle make",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateVehicleMakeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleMakeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vehicle-makes/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-makes"
                ],
                "summary": "Get a vehicle make",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle make id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleMakeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-makes"
                ],
                "summary": "Update a vehicle make",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle make id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vehicle make",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateVehicleMakeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleMakeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "vehicle-makes"
                ],
                "summary": "Delete a vehicle make",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle make id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vehicle-models": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-models"
                ],
                "summary": "List vehicle models",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleModelPage"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-models"
                ],
                "summary": "Create a vehicle model",
                "parameters": [
                    {
                        "description": "Vehicle model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateVehicleModelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleModelResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vehicle-models/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-models"
                ],
                "summary": "Get a vehicle model",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle model id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleModelResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-models"
                ],
                "summary": "Update a vehicle model",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle model id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vehicle model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateVehicleModelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleModelResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "vehicle-models"
                ],
                "summary": "Delete a vehicle model",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle model id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in with email and password",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenPair"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Exchange a refresh token for a new token pair",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "refresh",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenPair"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.TokenPair": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "dto.AssetPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AssetResponse"
                    }
                },
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.AssetResponse": {
            "type": "object",
            "properties": {
                "acquisition_date": {
                    "type": "string"
                },
                "acquisition_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "annual_percentage_rate": {
                    "type": "number"
                },
                "archived_at": {
                    "type": "string"
                },
                "asset_type_id": {
                    "type": "integer"
                },
                "body_subtype": {
                    "type": "string",
                    "maxLength": 100
                },
                "body_type": {
                    "type": "string",
                    "maxLength": 100
                },
                "capitalized_cost": {
                    "type": "number"
                },
                "color": {
                    "type": "string",
                    "maxLength": 50
                },
                "company_id": {
                    "type": "integer"
                },
                "current_meter": {
                    "type": "number"
                },
                "current_meter_date": {
                    "type": "string"
                },
                "custom_fields": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "down_payment": {
                    "type": "number"
                },
                "estimated_replacement_mileage": {
                    "type": "integer"
                },
                "estimated_resale_price": {
                    "type": "number"
                },
                "estimated_service_months": {
                    "type": "integer"
                },
                "excess_mileage_charge": {
                    "type": "number"
                },
                "external_id": {
                    "type": "string",
                    "maxLength": 100
                },
                "first_payment_date": {
                    "type": "string"
                },
                "fuel_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "fuel_volume_units": {
                    "type": "string",
                    "maxLength": 20
                },
                "generate_expenses": {
                    "type": "boolean"
                },
                "group": {
                    "type": "string",
                    "maxLength": 100
                },
                "id": {
                    "type": "integer"
                },
                "in_service_date": {
                    "type": "string"
                },
                "in_service_meter": {
                    "type": "number"
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "lease_end_date": {
                    "type": "string"
                },
                "lease_number": {
                    "type": "string",
                    "maxLength": 100
                },
                "lease_start_date": {
                    "type": "string"
                },
                "lease_vendor_id": {
                    "type": "integer"
                },
                "license_plate": {
                    "type": "string",
                    "maxLength": 20
                },
                "linked_vehicles": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "loan_account_number": {
                    "type": "string",
                    "maxLength": 100
                },
                "loan_amount": {
                    "type": "number"
                },
                "loan_end_date": {
                    "type": "string"
                },
                "loan_ended_at": {
                    "type": "string"
                },
                "loan_notes": {
                    "type": "string"
                },
                "loan_start_date": {
                    "type": "string"
                },
                "loan_started_at": {
                    "type": "string"
                },
                "loan_vendor_id": {
                    "type": "integer"
                },
                "make": {
                    "type": "string",
                    "maxLength": 100
                },
                "meter_unit": {
                    "type": "string",
                    "maxLength": 5
                },
                "mileage_cap": {
                    "type": "integer"
                },
                "model": {
                    "type": "string",
                    "maxLength": 100
                },
                "monthly_cost": {
                    "type": "number"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "msrp": {
                    "type": "number"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "notes": {
                    "type": "string"
                },
                "number_of_payments": {
                    "type": "integer"
                },
                "out_of_service_date": {
                    "type": "string"
                },
                "out_of_service_meter": {
                    "type": "number"
                },
                "owner_company_id": {
                    "type": "integer"
                },
                "ownership_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "photo": {
                    "type": "string",
                    "maxLength": 100
                },
                "purchase_date": {
                    "type": "string"
                },
                "purchase_meter": {
                    "type": "number"
                },
                "purchase_price": {
                    "type": "number"
                },
                "purchase_vendor": {
                    "type": "string",
                    "maxLength": 200
                },
                "registration_state": {
                    "type": "string",
                    "maxLength": 50
                },
                "residual_value": {
                    "type": "number"
                },
                "secondary_meter_unit": {
                    "type": "string",
                    "maxLength": 20
                },
                "secondary_meter_value": {
                    "type": "number"
                },
                "status_id": {
                    "type": "integer"
                },
                "trim": {
                    "type": "string",
                    "maxLength": 100
                },
                "updated_at": {
                    "type": "string"
                },
                "vehicle_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "vin_sn": {
                    "type": "string",
                    "maxLength": 100
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "dto.AssetStatusPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AssetStatusResponse"
                    }
                },
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.AssetStatusResponse": {
            "type": "object",
            "properties": {
                "color_code": {
                    "type": "string"
                },
                "company_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.AssetTypePage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AssetTypeResponse"
                    }
                },
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.AssetTypeResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "company_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.CatalogOptionPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CatalogOptionResponse"
                    }
                },
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.CatalogOptionResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "company_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "dto.CompanyPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CompanyResponse"
                    }
                },
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.CompanyResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "system_of_measurement": {
                    "type": "string"
                },
                "tax_id": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "dto.CreateAssetRequest": {
            "type": "object",
            "properties": {
                "acquisition_date": {
                    "type": "string"
                },
                "acquisition_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "annual_percentage_rate": {
                    "type": "number"
                },
                "archived_at": {
                    "type": "string"
                },
                "asset_type_id": {
                    "type": "integer"
                },
                "body_subtype": {
                    "type": "string",
                    "maxLength": 100
                },
                "body_type": {
                    "type": "string",
                    "maxLength": 100
                },
                "capitalized_cost": {
                    "type": "number"
                },
                "color": {
                    "type": "string",
                    "maxLength": 50
                },
                "current_meter": {
                    "type": "number"
                },
                "current_meter_date": {
                    "type": "string"
                },
                "custom_fields": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "down_payment": {
                    "type": "number"
                },
                "estimated_replacement_mileage": {
                    "type": "integer"
                },
                "estimated_resale_price": {
                    "type": "number"
                },
                "estimated_service_months": {
                    "type": "integer"
                },
                "excess_mileage_charge": {
                    "type": "number"
                },
                "external_id": {
                    "type": "string",
                    "maxLength": 100
                },
                "first_payment_date": {
                    "type": "string"
                },
                "fuel_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "fuel_volume_units": {
                    "type": "string",
                    "maxLength": 20
                },
                "generate_expenses": {
                    "type": "boolean"
                },
                "group": {
                    "type": "string",
                    "maxLength": 100
                },
                "in_service_date": {
                    "type": "string"
                },
                "in_service_meter": {
                    "type": "number"
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "lease_end_date": {
                    "type": "string"
                },
                "lease_number": {
                    "type": "string",
                    "maxLength": 100
                },
                "lease_start_date": {
                    "type": "string"
                },
                "lease_vendor_id": {
                    "type": "integer"
                },
                "license_plate": {
                    "type": "string",
                    "maxLength": 20
                },
                "linked_vehicles": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "loan_account_number": {
                    "type": "string",
                    "maxLength": 100
                },
                "loan_amount": {
                    "type": "number"
                },
                "loan_end_date": {
                    "type": "string"
                },
                "loan_ended_at": {
                    "type": "string"
                },
                "loan_notes": {
                    "type": "string"
                },
                "loan_start_date": {
                    "type": "string"
                },
                "loan_started_at": {
                    "type": "string"
                },
                "loan_vendor_id": {
                    "type": "integer"
                },
                "make": {
                    "type": "string",
                    "maxLength": 100
                },
                "meter_unit": {
                    "type": "string",
                    "maxLength": 5
                },
                "mileage_cap": {
                    "type": "integer"
                },
                "model": {
                    "type": "string",
                    "maxLength": 100
                },
                "monthly_cost": {
                    "type": "number"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "msrp": {
                    "type": "number"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "notes": {
                    "type": "string"
                },
                "number_of_payments": {
                    "type": "integer"
                },
                "out_of_service_date": {
                    "type": "string"
                },
                "out_of_service_meter": {
                    "type": "number"
                },
                "owner_company_id": {
                    "type": "integer"
                },
                "ownership_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "photo": {
                    "type": "string",
                    "maxLength": 100
                },
                "purchase_date": {
                    "type": "string"
                },
                "purchase_meter": {
                    "type": "number"
                },
                "purchase_price": {
                    "type": "number"
                },
                "purchase_vendor": {
                    "type": "string",
                    "maxLength": 200
                },
                "registration_state": {
                    "type": "string",
                    "maxLength": 50
                },
                "residual_value": {
                    "type": "number"
                },
                "secondary_meter_unit": {
                    "type": "string",
                    "maxLength": 20
                },
                "secondary_meter_value": {
                    "type": "number"
                },
                "status_id": {
                    "type": "integer"
                },
                "trim": {
                    "type": "string",
                    "maxLength": 100
                },
                "vehicle_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "vin_sn": {
                    "type": "string",
                    "maxLength": 100
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateAssetStatusRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "color_code": {
                    "type": "string",
                    "maxLength": 7
                },
                "name": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "dto.CreateAssetTypeRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "maxLength": 50
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.CreateCatalogOptionRequest": {
            "type": "object",
            "required": [
                "category",
                "value"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "maxLength": 30
                },
                "value": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.CreateCompanyRequest": {
            "type": "object",
            "required": [
                "name",
                "tax_id"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string",
                    "maxLength": 100
                },
                "country": {
                    "type": "string",
                    "maxLength": 50
                },
                "currency": {
                    "type": "string",
                    "maxLength": 3
                },
                "email": {
                    "type": "string",
                    "maxLength": 254
                },
                "logo": {
                    "type": "string",
                    "maxLength": 100
                },
                "name": {
                    "type": "string",
                    "maxLength": 200
                },
                "phone": {
                    "type": "string",
                    "maxLength": 20
                },
                "postal_code": {
                    "type": "string",
                    "maxLength": 20
                },
                "region": {
                    "type": "string",
                    "maxLength": 50
                },
                "system_of_measurement": {
                    "type": "string",
                    "enum": [
                        "metric",
                        "imperial"
                    ]
                },
                "tax_id": {
                    "type": "string",
                    "maxLength": 50
                },
                "timezone": {
                    "type": "string",
                    "maxLength": 50
                },
                "website": {
                    "type": "string",
                    "maxLength": 200
                }
            }
        },
        "dto.CreateVehicleMakeRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.CreateVehicleModelRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "make_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/dto.ErrorBody"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateAssetRequest": {
            "type": "object",
            "properties": {
                "acquisition_date": {
                    "type": "string"
                },
                "acquisition_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "annual_percentage_rate": {
                    "type": "number"
                },
                "archived_at": {
                    "type": "string"
                },
                "asset_type_id": {
                    "type": "integer"
                },
                "body_subtype": {
                    "type": "string",
                    "maxLength": 100
                },
                "body_type": {
                    "type": "string",
                    "maxLength": 100
                },
                "capitalized_cost": {
                    "type": "number"
                },
                "color": {
                    "type": "string",
                    "maxLength": 50
                },
                "current_meter": {
                    "type": "number"
                },
                "current_meter_date": {
                    "type": "string"
                },
                "custom_fields": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "down_payment": {
                    "type": "number"
                },
                "estimated_replacement_mileage": {
                    "type": "integer"
                },
                "estimated_resale_price": {
                    "type": "number"
                },
                "estimated_service_months": {
                    "type": "integer"
                },
                "excess_mileage_charge": {
                    "type": "number"
                },
                "external_id": {
                    "type": "string",
                    "maxLength": 100
                },
                "first_payment_date": {
                    "type": "string"
                },
                "fuel_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "fuel_volume_units": {
                    "type": "string",
                    "maxLength": 20
                },
                "generate_expenses": {
                    "type": "boolean"
                },
                "group": {
                    "type": "string",
                    "maxLength": 100
                },
                "in_service_date": {
                    "type": "string"
                },
                "in_service_meter": {
                    "type": "number"
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "lease_end_date": {
                    "type": "string"
                },
                "lease_number": {
                    "type": "string",
                    "maxLength": 100
                },
                "lease_start_date": {
                    "type": "string"
                },
                "lease_vendor_id": {
                    "type": "integer"
                },
                "license_plate": {
                    "type": "string",
                    "maxLength": 20
                },
                "linked_vehicles": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "loan_account_number": {
                    "type": "string",
                    "maxLength": 100
                },
                "loan_amount": {
                    "type": "number"
                },
                "loan_end_date": {
                    "type": "string"
                },
                "loan_ended_at": {
                    "type": "string"
                },
                "loan_notes": {
                    "type": "string"
                },
                "loan_start_date": {
                    "type": "string"
                },
                "loan_started_at": {
                    "type": "string"
                },
                "loan_vendor_id": {
                    "type": "integer"
                },
                "make": {
                    "type": "string",
                    "maxLength": 100
                },
                "meter_unit": {
                    "type": "string",
                    "maxLength": 5
                },
                "mileage_cap": {
                    "type": "integer"
                },
                "model": {
                    "type": "string",
                    "maxLength": 100
                },
                "monthly_cost": {
                    "type": "number"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "msrp": {
                    "type": "number"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "notes": {
                    "type": "string"
                },
                "number_of_payments": {
                    "type": "integer"
                },
                "out_of_service_date": {
                    "type": "string"
                },
                "out_of_service_meter": {
                    "type": "number"
                },
                "owner_company_id": {
                    "type": "integer"
                },
                "ownership_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "photo": {
                    "type": "string",
                    "maxLength": 100
                },
                "purchase_date": {
                    "type": "string"
                },
                "purchase_meter": {
                    "type": "number"
                },
                "purchase_price": {
                    "type": "number"
                },
                "purchase_vendor": {
                    "type": "string",
                    "maxLength": 200
                },
                "registration_state": {
                    "type": "string",
                    "maxLength": 50
                },
                "residual_value": {
                    "type": "number"
                },
                "secondary_meter_unit": {
                    "type": "string",
                    "maxLength": 20
                },
                "secondary_meter_value": {
                    "type": "number"
                },
                "status_id": {
                    "type": "integer"
                },
                "trim": {
                    "type": "string",
                    "maxLength": 100
                },
                "vehicle_type": {
                    "type": "string",
                    "maxLength": 20
                },
                "vin_sn": {
                    "type": "string",
                    "maxLength": 100
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateAssetStatusRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "color_code": {
                    "type": "string",
                    "maxLength": 7
                },
                "name": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "dto.UpdateAssetTypeRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "maxLength": 50
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.UpdateCatalogOptionRequest": {
            "type": "object",
            "required": [
                "category",
                "value"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "maxLength": 30
                },
                "value": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.UpdateCompanyRequest": {
            "type": "object",
            "required": [
                "name",
                "tax_id"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string",
                    "maxLength": 100
                },
                "country": {
                    "type": "string",
                    "maxLength": 50
                },
                "currency": {
                    "type": "string",
                    "maxLength": 3
                },
                "email": {
                    "type": "string",
                    "maxLength": 254
                },
                "logo": {
                    "type": "string",
                    "maxLength": 100
                },
                "name": {
                    "type": "string",
                    "maxLength": 200
                },
                "phone": {
                    "type": "string",
                    "maxLength": 20
                },
                "postal_code": {
                    "type": "string",
                    "maxLength": 20
                },
                "region": {
                    "type": "string",
                    "maxLength": 50
                },
                "system_of_measurement": {
                    "type": "string",
                    "enum": [
                        "metric",
                        "imperial"
                    ]
                },
                "tax_id": {
                    "type": "string",
                    "maxLength": 50
                },
                "timezone": {
                    "type": "string",
                    "maxLength": 50
                },
                "website": {
                    "type": "string",
                    "maxLength": 200
                }
            }
        },
        "dto.UpdateVehicleMakeRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.UpdateVehicleModelRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "make_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.VehicleMakePage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.VehicleMakeResponse"
                    }
                },
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.VehicleMakeResponse": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.VehicleModelPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.VehicleModelResponse"
                    }
                },
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.VehicleModelResponse": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "make_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "storage.Object": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Fleet API",
	Description:      "Go port of the fleet-management backend (auth, companies, uploads).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
